// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDecryptBody(arg1, arg2) {
  return window['go']['cryptokit']['Client']['BuildDecryptBody'](arg1, arg2);
}

export function Decrypt(arg1, arg2) {
  return window['go']['cryptokit']['Client']['Decrypt'](arg1, arg2);
}

export function Encrypt(arg1, arg2) {
  return window['go']['cryptokit']['Client']['Encrypt'](arg1, arg2);
}

export function EngageCodeSignProcess() {
  return window['go']['cryptokit']['Client']['EngageCodeSignProcess']();
}

export function GetKeyMetaJWK(arg1) {
  return window['go']['cryptokit']['Client']['GetKeyMetaJWK'](arg1);
}

export function GetKeys() {
  return window['go']['cryptokit']['Client']['GetKeys']();
}

export function GetKeysString() {
  return window['go']['cryptokit']['Client']['GetKeysString']();
}

export function MakeFileFromResponse(arg1) {
  return window['go']['cryptokit']['Client']['MakeFileFromResponse'](arg1);
}

export function Sign(arg1, arg2) {
  return window['go']['cryptokit']['Client']['Sign'](arg1, arg2);
}

export function Verify(arg1, arg2) {
  return window['go']['cryptokit']['Client']['Verify'](arg1, arg2);
}
