// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cryptokit} from '../models';

export function BuildDecryptBody(arg1:string):Promise<Array<number>>;

export function Decrypt(arg1:string):Promise<string>;

export function Encrypt(arg1:string,arg2:string):Promise<string>;

export function GetKeyMetaJWK(arg1:string):Promise<cryptokit.JWK>;

export function GetKeys():Promise<Array<cryptokit.Key>>;

export function GetKeysString():Promise<string>;

export function Sign(arg1:string):Promise<string>;

export function Verify(arg1:string,arg2:string):Promise<string>;
