// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Read() {
  return window['go']['storage']['Storage']['Read']();
}

export function Truncate() {
  return window['go']['storage']['Storage']['Truncate']();
}

export function Write(arg1) {
  return window['go']['storage']['Storage']['Write'](arg1);
}
