// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileOperation} from '../models';
import {context} from '../models';

export function GetFileExif(arg1:string):Promise<fileOperation.ExifResponse>;

export function GetFileInfo(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SetCtx(arg1:context.Context):Promise<void>;
