// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileExif(arg1) {
  return window['go']['fileOperation']['FileOperation']['GetFileExif'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['fileOperation']['FileOperation']['GetFileInfo'](arg1);
}

export function OpenFileDialog() {
  return window['go']['fileOperation']['FileOperation']['OpenFileDialog']();
}

export function SetCtx(arg1) {
  return window['go']['fileOperation']['FileOperation']['SetCtx'](arg1);
}
