services:

  
  database:
    build: 
      context: ../
      dockerfile: docker/database/Dockerfile
    container_name: database
    env_file:
      - ../.env
    ports:
      - "3306:3306"

  app:
    depends_on:
      - database
    build: 
      context: ../
      dockerfile: docker/webserver/Dockerfile
    container_name: app
    env_file:
      - ../.env
    tty: true
    expose:
      - "80"
    ports:
      - "8080:80"