version: '3.8'

services:

  
  database:
    build: 
      context: ../
      dockerfile: docker/database/Dockerfile
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    ports:
      - "3306:3306"

  app:
    depends_on:
      - database
    build: 
      context: ../
      dockerfile: docker/webserver/Dockerfile
    container_name: app
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      WORDPRESS_URL: http://localhost:8080/wordpress
    tty: true
    ports:
      - "8080:80"

