FROM ubuntu/mysql:latest
# Set MySQL configuration parameters using environment variables or custom config
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wpuser
ENV MYSQL_PASSWORD=wppassword

# Optionally, add a custom MySQL config file
# COPY my.cnf /etc/mysql/conf.d/