resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:the-marcules/standardLibrary.git
      branch: master
      private_key: ((git-private-key))

jobs:
  - name: my-pipe
    plan:
      - get: source-code
        trigger: true
      - task: prepare-files
        file: source-code/concourse/tasks/prepare-files.yml
      - task: run-tests
        file: source-code/concourse/tasks/run-tests.yml
      - task: build-go-app
        file: source-code/concourse/tasks/build-go-app.yml
      - task: run
        file: source-code/concourse/tasks/run.yml
